stages:
  fetch:
    cmd: python src/fetch_weather.py
    deps:
      - src/fetch_weather.py
    outs:
      - data/raw_data.csv
  preprocess:
    cmd: python src/preprocess_data.py
    deps:
      - src/preprocess_data.py
      - data/raw_data.csv
    outs:
      - data/processed_data.csv
  train:
    cmd: python src/train_model.py
    deps:
      - src/train_model.py
      - data/processed_data.csv
    outs:
      - models/model.pkl
